FROM node:16

RUN git clone https://github.com/docker-hy/material-applications.git
WORKDIR /material-applications/example-frontend
ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN node -v && npm -v
RUN npm install
RUN npm run build
RUN npm install -g serve
CMD serve -s -l 5000 build

EXPOSE 5000